### ISSUE TITLE
Service grid: Remove/change search bar filter has no effect

### ISSUE THREAD

**Issue by sukhwinder33445** [Icinga/icingadb-web#322] opened 2021-09-01 11:20 UTC
## Describe the bug
When the search bar filter is cleared/changed, only the URL is updated.  The page must be refreshed manually for the changed filter to take effect.

## Expected behavior
Filter should update automatically.

**Comment by sukhwinder33445** [comment] 2021-09-01 11:36
It works fine now, without any changes. Maybe my device was just too slow.

**Comment by nilmerg** [comment] 2021-09-01 11:57
Duplicate of #317

**Closed by nilmerg** 2021-09-01 11:57 UTC
Labels: no-issue
