### ISSUE TITLE
Change date display format for relative time/date

### ISSUE THREAD

**Issue by alamp1360** [Icinga/icingadb-web#1071] opened 2024-10-03 07:49 UTC
Icingaweb currently displays some dates in lists as a relative time, e.g. "1d 5h ago" or "on Sept 25".
When, for example, i try to find an alert in the "history" view of a service, that relative time display does not really help in finding an event. Instead, it is additional work to try (and fail) to recalculate the relative dates to an exact date.
Of course one could klick on an event to see the exact time, but that requires an extra step.

I guess one of you great developers of icingaweb2 invested a lot of time to realize that feature, but, at least for me it is not very helpful...
So i would suggest to implement some sort of "time display format" setting in the personal settings, where users could select either that relative format or an "exact timestamp".
My simple solution: Display a combination of the exact date and the relative time.
My "fix" would be something like this:

```
*** DateFormatter.php   2024-08-15 16:43:58.000000000 +0200
--- DateFormatter.php_new       2024-10-03 09:10:29.003981357 +0200
***************
*** 166,179 ****
                  // Move to next case
              case static::DATETIME:
                  $formatted = sprintf(
!                     t('on %s', 'An event happened on the given date or date and time'),
!                     $ago
                  );
                  break;
              case static::RELATIVE:
                  $formatted = sprintf(
!                     t('%s ago', 'An event that happened the given time interval ago'),
!                     $ago
                  );
                  break;
              case static::TIME:
--- 166,181 ----
                  // Move to next case
              case static::DATETIME:
                  $formatted = sprintf(
!                     t('%s (on %s)', 'An event happened on the given date or date and time'),
!                     date('Y-m-d H:i:s', (int) $time),
!                     $ago
                  );
                  break;
              case static::RELATIVE:
                  $formatted = sprintf(
!                     t('%s (%s ago)', 'An event that happened the given time interval ago'),
!                     date('Y-m-d H:i:s', (int) $time),
!                     $ago
                  );
                  break;
              case static::TIME:
```

**Comment by nilmerg** [comment] 2024-10-07 06:35
Duplicate of #1065

**Closed by nilmerg** 2024-10-07 06:35 UTC
