### ISSUE TITLE
Not all Services are listed in Overview Services

### ISSUE THREAD

**Issue by losten-git** [Icinga/icingadb-web#1023] opened 2024-05-16 11:51 UTC
## Describe the bug
I added a service to my host and attempted to locate it in Overview/Services. By default, it selects the common view. There are only two services listed instead of the expected three. In the bottom right corner, it also states that there are three services (see screenshots). When switching to the minimal view, all services are listed. When switching to the detailed view, it also only lists two services. Therefore, only in minimal view are all services listed correctly.

## Expected behavior
I expect to see all services to be listed, regardless which view is selected.

## Screenshots
![image](https://github.com/Icinga/icingadb-web/assets/116729378/b12cac51-9d23-4a17-873d-3216da53e1f8)
![image](https://github.com/Icinga/icingadb-web/assets/116729378/18462541-2336-4fc5-8eb8-6fcaea99db31)
![image](https://github.com/Icinga/icingadb-web/assets/116729378/63d26909-d750-4181-ab81-938644ef299a)

## Your Environment

* Icinga DB Web version (System - About): 1.1.2
* Icinga Web 2 version (System - About): 2.12.1
* Web browser: Chrome Version 124.0.6367.207
* Icinga 2 version (`icinga2 --version`): 2.14.2
* Icinga DB version (`icingadb --version`): 1.2.0
* PHP version used (`php --version`): 8.1.2
* Server operating system and version: Ubuntu 22.04

## Additional context
* /icingaweb2/icingadb/services?view=minimal&format=sql
<details>
SELECT service.id, service.environment_id, service.name_checksum, service.properties_checksum, service.host_id, service.name, service.name_ci, service.display_name, service.checkcommand_name, service.checkcommand_id, service.max_check_attempts, service.check_timeperiod_name, service.check_timeperiod_id, service.check_timeout, service.check_interval, service.check_retry_interval, service.active_checks_enabled, service.passive_checks_enabled, service.event_handler_enabled, service.notifications_enabled, service.flapping_enabled, service.flapping_threshold_low, service.flapping_threshold_high, service.perfdata_enabled, service.eventcommand_name, service.eventcommand_id, service.is_volatile, service.action_url_id, service.notes_url_id, service.notes, service.icon_image_id, service.icon_image_alt, service.zone_name, service.zone_id, service.command_endpoint_name, service.command_endpoint_id, service_state.service_id AS service_state_service_id, service_state.environment_id AS service_state_environment_id, service_state.state_type AS service_state_state_type, service_state.soft_state AS service_state_soft_state, service_state.hard_state AS service_state_hard_state, service_state.previous_soft_state AS service_state_previous_soft_state, service_state.previous_hard_state AS service_state_previous_hard_state, service_state.check_attempt AS service_state_check_attempt, service_state.severity AS service_state_severity, service_state.output AS service_state_output, service_state.long_output AS service_state_long_output, service_state.performance_data AS service_state_performance_data, service_state.normalized_performance_data AS service_state_normalized_performance_data, service_state.check_commandline AS service_state_check_commandline, service_state.is_problem AS service_state_is_problem, service_state.is_handled AS service_state_is_handled, service_state.is_reachable AS service_state_is_reachable, service_state.is_flapping AS service_state_is_flapping, service_state.is_overdue AS service_state_is_overdue, service_state.is_acknowledged AS service_state_is_acknowledged, service_state.acknowledgement_comment_id AS service_state_acknowledgement_comment_id, service_state_last_comment.id AS service_state_last_comment_id, service_state.in_downtime AS service_state_in_downtime, service_state.execution_time AS service_state_execution_time, service_state.latency AS service_state_latency, service_state.check_timeout AS service_state_check_timeout, service_state.check_source AS service_state_check_source, service_state.scheduling_source AS service_state_scheduling_source, service_state.last_update AS service_state_last_update, service_state.last_state_change AS service_state_last_state_change, service_state.next_check AS service_state_next_check, service_state.next_update AS service_state_next_update, service_state_last_comment.environment_id AS service_state_last_comment_environment_id, service_state_last_comment.object_type AS service_state_last_comment_object_type, service_state_last_comment.host_id AS service_state_last_comment_host_id, service_state_last_comment.service_id AS service_state_last_comment_service_id, service_state_last_comment.name_checksum AS service_state_last_comment_name_checksum, service_state_last_comment.properties_checksum AS service_state_last_comment_properties_checksum, service_state_last_comment.name AS service_state_last_comment_name, service_state_last_comment.author AS service_state_last_comment_author, service_state_last_comment.text AS service_state_last_comment_text, service_state_last_comment.entry_type AS service_state_last_comment_entry_type, service_state_last_comment.entry_time AS service_state_last_comment_entry_time, service_state_last_comment.is_persistent AS service_state_last_comment_is_persistent, service_state_last_comment.is_sticky AS service_state_last_comment_is_sticky, service_state_last_comment.expire_time AS service_state_last_comment_expire_time, service_state_last_comment.zone_id AS service_state_last_comment_zone_id, service_host.id AS service_host_id, service_host.environment_id AS service_host_environment_id, service_host.name_checksum AS service_host_name_checksum, service_host.properties_checksum AS service_host_properties_checksum, service_host.name AS service_host_name, service_host.name_ci AS service_host_name_ci, service_host.display_name AS service_host_display_name, service_host.address AS service_host_address, service_host.address6 AS service_host_address6, service_host.address_bin AS service_host_address_bin, service_host.address6_bin AS service_host_address6_bin, service_host.checkcommand_name AS service_host_checkcommand_name, service_host.checkcommand_id AS service_host_checkcommand_id, service_host.max_check_attempts AS service_host_max_check_attempts, service_host.check_timeperiod_name AS service_host_check_timeperiod_name, service_host.check_timeperiod_id AS service_host_check_timeperiod_id, service_host.check_timeout AS service_host_check_timeout, service_host.check_interval AS service_host_check_interval, service_host.check_retry_interval AS service_host_check_retry_interval, service_host.active_checks_enabled AS service_host_active_checks_enabled, service_host.passive_checks_enabled AS service_host_passive_checks_enabled, service_host.event_handler_enabled AS service_host_event_handler_enabled, service_host.notifications_enabled AS service_host_notifications_enabled, service_host.flapping_enabled AS service_host_flapping_enabled, service_host.flapping_threshold_low AS service_host_flapping_threshold_low, service_host.flapping_threshold_high AS service_host_flapping_threshold_high, service_host.perfdata_enabled AS service_host_perfdata_enabled, service_host.eventcommand_name AS service_host_eventcommand_name, service_host.eventcommand_id AS service_host_eventcommand_id, service_host.is_volatile AS service_host_is_volatile, service_host.action_url_id AS service_host_action_url_id, service_host.notes_url_id AS service_host_notes_url_id, service_host.notes AS service_host_notes, service_host.icon_image_id AS service_host_icon_image_id, service_host.icon_image_alt AS service_host_icon_image_alt, service_host.zone_name AS service_host_zone_name, service_host.zone_id AS service_host_zone_id, service_host.command_endpoint_name AS service_host_command_endpoint_name, service_host.command_endpoint_id AS service_host_command_endpoint_id, service_host_state.host_id AS service_host_state_host_id, service_host_state.environment_id AS service_host_state_environment_id, service_host_state.state_type AS service_host_state_state_type, service_host_state.soft_state AS service_host_state_soft_state, service_host_state.hard_state AS service_host_state_hard_state, service_host_state.previous_soft_state AS service_host_state_previous_soft_state, service_host_state.previous_hard_state AS service_host_state_previous_hard_state, service_host_state.check_attempt AS service_host_state_check_attempt, service_host_state.severity AS service_host_state_severity, service_host_state.output AS service_host_state_output, service_host_state.long_output AS service_host_state_long_output, service_host_state.performance_data AS service_host_state_performance_data, service_host_state.normalized_performance_data AS service_host_state_normalized_performance_data, service_host_state.check_commandline AS service_host_state_check_commandline, service_host_state.is_problem AS service_host_state_is_problem, service_host_state.is_handled AS service_host_state_is_handled, service_host_state.is_reachable AS service_host_state_is_reachable, service_host_state.is_flapping AS service_host_state_is_flapping, service_host_state.is_overdue AS service_host_state_is_overdue, service_host_state.is_acknowledged AS service_host_state_is_acknowledged, service_host_state.acknowledgement_comment_id AS service_host_state_acknowledgement_comment_id, service_host_state.last_comment_id AS service_host_state_last_comment_id, service_host_state.in_downtime AS service_host_state_in_downtime, service_host_state.execution_time AS service_host_state_execution_time, service_host_state.latency AS service_host_state_latency, service_host_state.check_timeout AS service_host_state_check_timeout, service_host_state.check_source AS service_host_state_check_source, service_host_state.scheduling_source AS service_host_state_scheduling_source, service_host_state.last_update AS service_host_state_last_update, service_host_state.last_state_change AS service_host_state_last_state_change, service_host_state.next_check AS service_host_state_next_check, service_host_state.next_update AS service_host_state_next_update, service_icon_image.id AS service_icon_image_id, service_icon_image.icon_image AS service_icon_image_icon_image, service_icon_image.environment_id AS service_icon_image_environment_id FROM service INNER JOIN service_state ON service_state.service_id = service.id LEFT JOIN comment service_state_last_comment ON service_state_last_comment.id = service_state.last_comment_id LEFT JOIN host service_host ON service_host.id = service.host_id LEFT JOIN host_state service_host_state ON service_host_state.host_id = service_host.id LEFT JOIN icon_image service_icon_image ON service_icon_image.id = service.icon_image_id ORDER BY service.display_name LIMIT 50

SELECT (SUM(CASE WHEN service_state.is_acknowledged = 'y' THEN 1 ELSE 0 END)) AS services_acknowledged, (SUM(CASE WHEN service.active_checks_enabled = 'y' THEN 1 ELSE 0 END)) AS services_active_checks_enabled, (SUM(CASE WHEN service.passive_checks_enabled = 'y' THEN 1 ELSE 0 END)) AS services_passive_checks_enabled, (SUM(CASE WHEN service_state.soft_state = 2 AND (service_state.is_handled = 'y' OR service_state.is_reachable = 'n') THEN 1 ELSE 0 END)) AS services_critical_handled, (SUM(CASE WHEN service_state.soft_state = 2 AND service_state.is_handled = 'n' AND service_state.is_reachable = 'y' THEN 1 ELSE 0 END)) AS services_critical_unhandled, (SUM(CASE WHEN service.event_handler_enabled = 'y' THEN 1 ELSE 0 END)) AS services_event_handler_enabled, (SUM(CASE WHEN service.flapping_enabled = 'y' THEN 1 ELSE 0 END)) AS services_flapping_enabled, (SUM(CASE WHEN service.notifications_enabled = 'y' THEN 1 ELSE 0 END)) AS services_notifications_enabled, (SUM(CASE WHEN service_state.soft_state = 0 THEN 1 ELSE 0 END)) AS services_ok, (SUM(CASE WHEN service_state.soft_state = 99 THEN 1 ELSE 0 END)) AS services_pending, (SUM(CASE WHEN service_state.is_problem = 'y' AND service_state.is_acknowledged = 'n' THEN 1 ELSE 0 END)) AS services_problems_unacknowledged, (SUM(CASE WHEN service.id IS NOT NULL THEN 1 ELSE 0 END)) AS services_total, (SUM(CASE WHEN service_state.soft_state = 3 AND (service_state.is_handled = 'y' OR service_state.is_reachable = 'n') THEN 1 ELSE 0 END)) AS services_unknown_handled, (SUM(CASE WHEN service_state.soft_state = 3 AND service_state.is_handled = 'n' AND service_state.is_reachable = 'y' THEN 1 ELSE 0 END)) AS services_unknown_unhandled, (SUM(CASE WHEN service_state.soft_state = 1 AND (service_state.is_handled = 'y' OR service_state.is_reachable = 'n') THEN 1 ELSE 0 END)) AS services_warning_handled, (SUM(CASE WHEN service_state.soft_state = 1 AND service_state.is_handled = 'n' AND service_state.is_reachable = 'y' THEN 1 ELSE 0 END)) AS services_warning_unhandled FROM service LEFT JOIN service_state ON service_state.service_id = service.id
</details>

* /icingaweb2/icingadb/services?view=common&format=sql
<details>
SELECT service.id, service.environment_id, service.name_checksum, service.properties_checksum, service.host_id, service.name, service.name_ci, service.display_name, service.checkcommand_name, service.checkcommand_id, service.max_check_attempts, service.check_timeperiod_name, service.check_timeperiod_id, service.check_timeout, service.check_interval, service.check_retry_interval, service.active_checks_enabled, service.passive_checks_enabled, service.event_handler_enabled, service.notifications_enabled, service.flapping_enabled, service.flapping_threshold_low, service.flapping_threshold_high, service.perfdata_enabled, service.eventcommand_name, service.eventcommand_id, service.is_volatile, service.action_url_id, service.notes_url_id, service.notes, service.icon_image_id, service.icon_image_alt, service.zone_name, service.zone_id, service.command_endpoint_name, service.command_endpoint_id, service_state.service_id AS service_state_service_id, service_state.environment_id AS service_state_environment_id, service_state.state_type AS service_state_state_type, service_state.soft_state AS service_state_soft_state, service_state.hard_state AS service_state_hard_state, service_state.previous_soft_state AS service_state_previous_soft_state, service_state.previous_hard_state AS service_state_previous_hard_state, service_state.check_attempt AS service_state_check_attempt, service_state.severity AS service_state_severity, service_state.output AS service_state_output, service_state.long_output AS service_state_long_output, service_state.performance_data AS service_state_performance_data, service_state.normalized_performance_data AS service_state_normalized_performance_data, service_state.check_commandline AS service_state_check_commandline, service_state.is_problem AS service_state_is_problem, service_state.is_handled AS service_state_is_handled, service_state.is_reachable AS service_state_is_reachable, service_state.is_flapping AS service_state_is_flapping, service_state.is_overdue AS service_state_is_overdue, service_state.is_acknowledged AS service_state_is_acknowledged, service_state.acknowledgement_comment_id AS service_state_acknowledgement_comment_id, service_state_last_comment.id AS service_state_last_comment_id, service_state.in_downtime AS service_state_in_downtime, service_state.execution_time AS service_state_execution_time, service_state.latency AS service_state_latency, service_state.check_timeout AS service_state_check_timeout, service_state.check_source AS service_state_check_source, service_state.scheduling_source AS service_state_scheduling_source, service_state.last_update AS service_state_last_update, service_state.last_state_change AS service_state_last_state_change, service_state.next_check AS service_state_next_check, service_state.next_update AS service_state_next_update, service_state_last_comment.environment_id AS service_state_last_comment_environment_id, service_state_last_comment.object_type AS service_state_last_comment_object_type, service_state_last_comment.host_id AS service_state_last_comment_host_id, service_state_last_comment.service_id AS service_state_last_comment_service_id, service_state_last_comment.name_checksum AS service_state_last_comment_name_checksum, service_state_last_comment.properties_checksum AS service_state_last_comment_properties_checksum, service_state_last_comment.name AS service_state_last_comment_name, service_state_last_comment.author AS service_state_last_comment_author, service_state_last_comment.text AS service_state_last_comment_text, service_state_last_comment.entry_type AS service_state_last_comment_entry_type, service_state_last_comment.entry_time AS service_state_last_comment_entry_time, service_state_last_comment.is_persistent AS service_state_last_comment_is_persistent, service_state_last_comment.is_sticky AS service_state_last_comment_is_sticky, service_state_last_comment.expire_time AS service_state_last_comment_expire_time, service_state_last_comment.zone_id AS service_state_last_comment_zone_id, service_host.id AS service_host_id, service_host.environment_id AS service_host_environment_id, service_host.name_checksum AS service_host_name_checksum, service_host.properties_checksum AS service_host_properties_checksum, service_host.name AS service_host_name, service_host.name_ci AS service_host_name_ci, service_host.display_name AS service_host_display_name, service_host.address AS service_host_address, service_host.address6 AS service_host_address6, service_host.address_bin AS service_host_address_bin, service_host.address6_bin AS service_host_address6_bin, service_host.checkcommand_name AS service_host_checkcommand_name, service_host.checkcommand_id AS service_host_checkcommand_id, service_host.max_check_attempts AS service_host_max_check_attempts, service_host.check_timeperiod_name AS service_host_check_timeperiod_name, service_host.check_timeperiod_id AS service_host_check_timeperiod_id, service_host.check_timeout AS service_host_check_timeout, service_host.check_interval AS service_host_check_interval, service_host.check_retry_interval AS service_host_check_retry_interval, service_host.active_checks_enabled AS service_host_active_checks_enabled, service_host.passive_checks_enabled AS service_host_passive_checks_enabled, service_host.event_handler_enabled AS service_host_event_handler_enabled, service_host.notifications_enabled AS service_host_notifications_enabled, service_host.flapping_enabled AS service_host_flapping_enabled, service_host.flapping_threshold_low AS service_host_flapping_threshold_low, service_host.flapping_threshold_high AS service_host_flapping_threshold_high, service_host.perfdata_enabled AS service_host_perfdata_enabled, service_host.eventcommand_name AS service_host_eventcommand_name, service_host.eventcommand_id AS service_host_eventcommand_id, service_host.is_volatile AS service_host_is_volatile, service_host.action_url_id AS service_host_action_url_id, service_host.notes_url_id AS service_host_notes_url_id, service_host.notes AS service_host_notes, service_host.icon_image_id AS service_host_icon_image_id, service_host.icon_image_alt AS service_host_icon_image_alt, service_host.zone_name AS service_host_zone_name, service_host.zone_id AS service_host_zone_id, service_host.command_endpoint_name AS service_host_command_endpoint_name, service_host.command_endpoint_id AS service_host_command_endpoint_id, service_host_state.host_id AS service_host_state_host_id, service_host_state.environment_id AS service_host_state_environment_id, service_host_state.state_type AS service_host_state_state_type, service_host_state.soft_state AS service_host_state_soft_state, service_host_state.hard_state AS service_host_state_hard_state, service_host_state.previous_soft_state AS service_host_state_previous_soft_state, service_host_state.previous_hard_state AS service_host_state_previous_hard_state, service_host_state.check_attempt AS service_host_state_check_attempt, service_host_state.severity AS service_host_state_severity, service_host_state.output AS service_host_state_output, service_host_state.long_output AS service_host_state_long_output, service_host_state.performance_data AS service_host_state_performance_data, service_host_state.normalized_performance_data AS service_host_state_normalized_performance_data, service_host_state.check_commandline AS service_host_state_check_commandline, service_host_state.is_problem AS service_host_state_is_problem, service_host_state.is_handled AS service_host_state_is_handled, service_host_state.is_reachable AS service_host_state_is_reachable, service_host_state.is_flapping AS service_host_state_is_flapping, service_host_state.is_overdue AS service_host_state_is_overdue, service_host_state.is_acknowledged AS service_host_state_is_acknowledged, service_host_state.acknowledgement_comment_id AS service_host_state_acknowledgement_comment_id, service_host_state.last_comment_id AS service_host_state_last_comment_id, service_host_state.in_downtime AS service_host_state_in_downtime, service_host_state.execution_time AS service_host_state_execution_time, service_host_state.latency AS service_host_state_latency, service_host_state.check_timeout AS service_host_state_check_timeout, service_host_state.check_source AS service_host_state_check_source, service_host_state.scheduling_source AS service_host_state_scheduling_source, service_host_state.last_update AS service_host_state_last_update, service_host_state.last_state_change AS service_host_state_last_state_change, service_host_state.next_check AS service_host_state_next_check, service_host_state.next_update AS service_host_state_next_update, service_icon_image.id AS service_icon_image_id, service_icon_image.icon_image AS service_icon_image_icon_image, service_icon_image.environment_id AS service_icon_image_environment_id FROM service INNER JOIN service_state ON service_state.service_id = service.id LEFT JOIN comment service_state_last_comment ON service_state_last_comment.id = service_state.last_comment_id LEFT JOIN host service_host ON service_host.id = service.host_id LEFT JOIN host_state service_host_state ON service_host_state.host_id = service_host.id LEFT JOIN icon_image service_icon_image ON service_icon_image.id = service.icon_image_id ORDER BY service.display_name LIMIT 25

SELECT (SUM(CASE WHEN service_state.is_acknowledged = 'y' THEN 1 ELSE 0 END)) AS services_acknowledged, (SUM(CASE WHEN service.active_checks_enabled = 'y' THEN 1 ELSE 0 END)) AS services_active_checks_enabled, (SUM(CASE WHEN service.passive_checks_enabled = 'y' THEN 1 ELSE 0 END)) AS services_passive_checks_enabled, (SUM(CASE WHEN service_state.soft_state = 2 AND (service_state.is_handled = 'y' OR service_state.is_reachable = 'n') THEN 1 ELSE 0 END)) AS services_critical_handled, (SUM(CASE WHEN service_state.soft_state = 2 AND service_state.is_handled = 'n' AND service_state.is_reachable = 'y' THEN 1 ELSE 0 END)) AS services_critical_unhandled, (SUM(CASE WHEN service.event_handler_enabled = 'y' THEN 1 ELSE 0 END)) AS services_event_handler_enabled, (SUM(CASE WHEN service.flapping_enabled = 'y' THEN 1 ELSE 0 END)) AS services_flapping_enabled, (SUM(CASE WHEN service.notifications_enabled = 'y' THEN 1 ELSE 0 END)) AS services_notifications_enabled, (SUM(CASE WHEN service_state.soft_state = 0 THEN 1 ELSE 0 END)) AS services_ok, (SUM(CASE WHEN service_state.soft_state = 99 THEN 1 ELSE 0 END)) AS services_pending, (SUM(CASE WHEN service_state.is_problem = 'y' AND service_state.is_acknowledged = 'n' THEN 1 ELSE 0 END)) AS services_problems_unacknowledged, (SUM(CASE WHEN service.id IS NOT NULL THEN 1 ELSE 0 END)) AS services_total, (SUM(CASE WHEN service_state.soft_state = 3 AND (service_state.is_handled = 'y' OR service_state.is_reachable = 'n') THEN 1 ELSE 0 END)) AS services_unknown_handled, (SUM(CASE WHEN service_state.soft_state = 3 AND service_state.is_handled = 'n' AND service_state.is_reachable = 'y' THEN 1 ELSE 0 END)) AS services_unknown_unhandled, (SUM(CASE WHEN service_state.soft_state = 1 AND (service_state.is_handled = 'y' OR service_state.is_reachable = 'n') THEN 1 ELSE 0 END)) AS services_warning_handled, (SUM(CASE WHEN service_state.soft_state = 1 AND service_state.is_handled = 'n' AND service_state.is_reachable = 'y' THEN 1 ELSE 0 END)) AS services_warning_unhandled FROM service LEFT JOIN service_state ON service_state.service_id = service.id
</details>

* /icingaweb2/icingadb/services?view=detailed&format=sql
<details>
SELECT service.id, service.environment_id, service.name_checksum, service.properties_checksum, service.host_id, service.name, service.name_ci, service.display_name, service.checkcommand_name, service.checkcommand_id, service.max_check_attempts, service.check_timeperiod_name, service.check_timeperiod_id, service.check_timeout, service.check_interval, service.check_retry_interval, service.active_checks_enabled, service.passive_checks_enabled, service.event_handler_enabled, service.notifications_enabled, service.flapping_enabled, service.flapping_threshold_low, service.flapping_threshold_high, service.perfdata_enabled, service.eventcommand_name, service.eventcommand_id, service.is_volatile, service.action_url_id, service.notes_url_id, service.notes, service.icon_image_id, service.icon_image_alt, service.zone_name, service.zone_id, service.command_endpoint_name, service.command_endpoint_id, service_state.service_id AS service_state_service_id, service_state.environment_id AS service_state_environment_id, service_state.state_type AS service_state_state_type, service_state.soft_state AS service_state_soft_state, service_state.hard_state AS service_state_hard_state, service_state.previous_soft_state AS service_state_previous_soft_state, service_state.previous_hard_state AS service_state_previous_hard_state, service_state.check_attempt AS service_state_check_attempt, service_state.severity AS service_state_severity, service_state.output AS service_state_output, service_state.long_output AS service_state_long_output, service_state.performance_data AS service_state_performance_data, service_state.normalized_performance_data AS service_state_normalized_performance_data, service_state.check_commandline AS service_state_check_commandline, service_state.is_problem AS service_state_is_problem, service_state.is_handled AS service_state_is_handled, service_state.is_reachable AS service_state_is_reachable, service_state.is_flapping AS service_state_is_flapping, service_state.is_overdue AS service_state_is_overdue, service_state.is_acknowledged AS service_state_is_acknowledged, service_state.acknowledgement_comment_id AS service_state_acknowledgement_comment_id, service_state_last_comment.id AS service_state_last_comment_id, service_state.in_downtime AS service_state_in_downtime, service_state.execution_time AS service_state_execution_time, service_state.latency AS service_state_latency, service_state.check_timeout AS service_state_check_timeout, service_state.check_source AS service_state_check_source, service_state.scheduling_source AS service_state_scheduling_source, service_state.last_update AS service_state_last_update, service_state.last_state_change AS service_state_last_state_change, service_state.next_check AS service_state_next_check, service_state.next_update AS service_state_next_update, service_state_last_comment.environment_id AS service_state_last_comment_environment_id, service_state_last_comment.object_type AS service_state_last_comment_object_type, service_state_last_comment.host_id AS service_state_last_comment_host_id, service_state_last_comment.service_id AS service_state_last_comment_service_id, service_state_last_comment.name_checksum AS service_state_last_comment_name_checksum, service_state_last_comment.properties_checksum AS service_state_last_comment_properties_checksum, service_state_last_comment.name AS service_state_last_comment_name, service_state_last_comment.author AS service_state_last_comment_author, service_state_last_comment.text AS service_state_last_comment_text, service_state_last_comment.entry_type AS service_state_last_comment_entry_type, service_state_last_comment.entry_time AS service_state_last_comment_entry_time, service_state_last_comment.is_persistent AS service_state_last_comment_is_persistent, service_state_last_comment.is_sticky AS service_state_last_comment_is_sticky, service_state_last_comment.expire_time AS service_state_last_comment_expire_time, service_state_last_comment.zone_id AS service_state_last_comment_zone_id, service_host.id AS service_host_id, service_host.environment_id AS service_host_environment_id, service_host.name_checksum AS service_host_name_checksum, service_host.properties_checksum AS service_host_properties_checksum, service_host.name AS service_host_name, service_host.name_ci AS service_host_name_ci, service_host.display_name AS service_host_display_name, service_host.address AS service_host_address, service_host.address6 AS service_host_address6, service_host.address_bin AS service_host_address_bin, service_host.address6_bin AS service_host_address6_bin, service_host.checkcommand_name AS service_host_checkcommand_name, service_host.checkcommand_id AS service_host_checkcommand_id, service_host.max_check_attempts AS service_host_max_check_attempts, service_host.check_timeperiod_name AS service_host_check_timeperiod_name, service_host.check_timeperiod_id AS service_host_check_timeperiod_id, service_host.check_timeout AS service_host_check_timeout, service_host.check_interval AS service_host_check_interval, service_host.check_retry_interval AS service_host_check_retry_interval, service_host.active_checks_enabled AS service_host_active_checks_enabled, service_host.passive_checks_enabled AS service_host_passive_checks_enabled, service_host.event_handler_enabled AS service_host_event_handler_enabled, service_host.notifications_enabled AS service_host_notifications_enabled, service_host.flapping_enabled AS service_host_flapping_enabled, service_host.flapping_threshold_low AS service_host_flapping_threshold_low, service_host.flapping_threshold_high AS service_host_flapping_threshold_high, service_host.perfdata_enabled AS service_host_perfdata_enabled, service_host.eventcommand_name AS service_host_eventcommand_name, service_host.eventcommand_id AS service_host_eventcommand_id, service_host.is_volatile AS service_host_is_volatile, service_host.action_url_id AS service_host_action_url_id, service_host.notes_url_id AS service_host_notes_url_id, service_host.notes AS service_host_notes, service_host.icon_image_id AS service_host_icon_image_id, service_host.icon_image_alt AS service_host_icon_image_alt, service_host.zone_name AS service_host_zone_name, service_host.zone_id AS service_host_zone_id, service_host.command_endpoint_name AS service_host_command_endpoint_name, service_host.command_endpoint_id AS service_host_command_endpoint_id, service_host_state.host_id AS service_host_state_host_id, service_host_state.environment_id AS service_host_state_environment_id, service_host_state.state_type AS service_host_state_state_type, service_host_state.soft_state AS service_host_state_soft_state, service_host_state.hard_state AS service_host_state_hard_state, service_host_state.previous_soft_state AS service_host_state_previous_soft_state, service_host_state.previous_hard_state AS service_host_state_previous_hard_state, service_host_state.check_attempt AS service_host_state_check_attempt, service_host_state.severity AS service_host_state_severity, service_host_state.output AS service_host_state_output, service_host_state.long_output AS service_host_state_long_output, service_host_state.performance_data AS service_host_state_performance_data, service_host_state.normalized_performance_data AS service_host_state_normalized_performance_data, service_host_state.check_commandline AS service_host_state_check_commandline, service_host_state.is_problem AS service_host_state_is_problem, service_host_state.is_handled AS service_host_state_is_handled, service_host_state.is_reachable AS service_host_state_is_reachable, service_host_state.is_flapping AS service_host_state_is_flapping, service_host_state.is_overdue AS service_host_state_is_overdue, service_host_state.is_acknowledged AS service_host_state_is_acknowledged, service_host_state.acknowledgement_comment_id AS service_host_state_acknowledgement_comment_id, service_host_state.last_comment_id AS service_host_state_last_comment_id, service_host_state.in_downtime AS service_host_state_in_downtime, service_host_state.execution_time AS service_host_state_execution_time, service_host_state.latency AS service_host_state_latency, service_host_state.check_timeout AS service_host_state_check_timeout, service_host_state.check_source AS service_host_state_check_source, service_host_state.scheduling_source AS service_host_state_scheduling_source, service_host_state.last_update AS service_host_state_last_update, service_host_state.last_state_change AS service_host_state_last_state_change, service_host_state.next_check AS service_host_state_next_check, service_host_state.next_update AS service_host_state_next_update, service_icon_image.id AS service_icon_image_id, service_icon_image.icon_image AS service_icon_image_icon_image, service_icon_image.environment_id AS service_icon_image_environment_id FROM service INNER JOIN service_state ON service_state.service_id = service.id LEFT JOIN comment service_state_last_comment ON service_state_last_comment.id = service_state.last_comment_id LEFT JOIN host service_host ON service_host.id = service.host_id LEFT JOIN host_state service_host_state ON service_host_state.host_id = service_host.id LEFT JOIN icon_image service_icon_image ON service_icon_image.id = service.icon_image_id ORDER BY service.display_name LIMIT 25

SELECT (SUM(CASE WHEN service_state.is_acknowledged = 'y' THEN 1 ELSE 0 END)) AS services_acknowledged, (SUM(CASE WHEN service.active_checks_enabled = 'y' THEN 1 ELSE 0 END)) AS services_active_checks_enabled, (SUM(CASE WHEN service.passive_checks_enabled = 'y' THEN 1 ELSE 0 END)) AS services_passive_checks_enabled, (SUM(CASE WHEN service_state.soft_state = 2 AND (service_state.is_handled = 'y' OR service_state.is_reachable = 'n') THEN 1 ELSE 0 END)) AS services_critical_handled, (SUM(CASE WHEN service_state.soft_state = 2 AND service_state.is_handled = 'n' AND service_state.is_reachable = 'y' THEN 1 ELSE 0 END)) AS services_critical_unhandled, (SUM(CASE WHEN service.event_handler_enabled = 'y' THEN 1 ELSE 0 END)) AS services_event_handler_enabled, (SUM(CASE WHEN service.flapping_enabled = 'y' THEN 1 ELSE 0 END)) AS services_flapping_enabled, (SUM(CASE WHEN service.notifications_enabled = 'y' THEN 1 ELSE 0 END)) AS services_notifications_enabled, (SUM(CASE WHEN service_state.soft_state = 0 THEN 1 ELSE 0 END)) AS services_ok, (SUM(CASE WHEN service_state.soft_state = 99 THEN 1 ELSE 0 END)) AS services_pending, (SUM(CASE WHEN service_state.is_problem = 'y' AND service_state.is_acknowledged = 'n' THEN 1 ELSE 0 END)) AS services_problems_unacknowledged, (SUM(CASE WHEN service.id IS NOT NULL THEN 1 ELSE 0 END)) AS services_total, (SUM(CASE WHEN service_state.soft_state = 3 AND (service_state.is_handled = 'y' OR service_state.is_reachable = 'n') THEN 1 ELSE 0 END)) AS services_unknown_handled, (SUM(CASE WHEN service_state.soft_state = 3 AND service_state.is_handled = 'n' AND service_state.is_reachable = 'y' THEN 1 ELSE 0 END)) AS services_unknown_unhandled, (SUM(CASE WHEN service_state.soft_state = 1 AND (service_state.is_handled = 'y' OR service_state.is_reachable = 'n') THEN 1 ELSE 0 END)) AS services_warning_handled, (SUM(CASE WHEN service_state.soft_state = 1 AND service_state.is_handled = 'n' AND service_state.is_reachable = 'y' THEN 1 ELSE 0 END)) AS services_warning_unhandled FROM service LEFT JOIN service_state ON service_state.service_id = service.id
</details>

**Comment by RincewindsHat** [comment] 2024-05-23 13:36
Possible Duplicate of #1012

**Comment by sukhwinder33445** [comment] 2024-06-03 11:03
Hi @losten-git,

I could not reproduce this behaviour. Can you please provide me more information, e.g. whether you have configured any restrictions and how you configure the objects?

**Closed** 2024-06-03 11:28 UTC
