### ISSUE TITLE
Host/service filtering != for costumvar not working correctly

### ISSUE THREAD

**Issue by gbin2265** [Icinga/icingadb-web#865] opened 2023-09-06 22:28 UTC
## Describe the bug
when I do a filtering on the host or service list it doesn't use the != operand correctly in the sql statement.
He converts it as = in the sql and not as !=

## To Reproduce
do a basic filtering on the host/service list for a customvar with the operand != and check the sql statement (format=sql).

## Expected behavior
I expect to see all services that do not have a value of 1 for the custumvar or that the custumvar does not exist for the service

## sql 
This you see with the format=sql
```

	where
		(sub_customvar_flat.flatvalue = '1')
			and (sub_customvar_flat.flatname = 'variablename')
			
	where
		sub_customvar_flat.flatname = 'variablename'))))


```
For me must this be 

`flatvalue != '1' 
`

and the second part 

`flatname != 'variablename'
`

## Your Environment
Latest snapshot for centos 7 on 23/09/02

regards,
Geert

**Comment by yhabteab** [comment] 2023-09-07 10:50
Hi @gbin2265, these `where clauses` are for the subqueries, but the subqueries themselves are wrapped by either the sql `IN()` or `NOT IN()` operators, so this is actually not a bug. But while trying to reproduce your issue, we encountered another [serious bug](https://github.com/Icinga/ipl-orm/issues/119) that also affects the outcome you expect (filtering for hosts/services that don't set customvar to `1` or not at all).

**Comment by gbin2265** [comment] 2023-09-07 13:31
I am not an SQL/PHP specialist, but there was something wrong that I did not get the correct output.

Thank you for your support to resolve this issue.

**Comment by nilmerg** [comment] 2024-02-14 15:54
This is related to https://github.com/Icinga/ipl-orm/pull/13 and can be fixed by commenting out [this](https://github.com/Icinga/ipl-orm/commit/82d224bb757c0e505d4ce70af9ae390c06054c38#diff-72ba3d20f26f0cfa3a0647c19d28a13290809f3217ea1e909c131eb2e6552212R222) line. Though, cases (thankfully) mentioned in https://github.com/Icinga/ipl-orm/pull/13 are not working anymore then.

**Comment by nilmerg** [comment] 2024-03-13 13:37
ref/IP/52121

**Closed** 2024-03-22 14:04 UTC
Labels: bug, ref/IP
