### ISSUE TITLE
Action links

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingadb-web#56] opened 2020-04-17 05:56 UTC
Action links like "Modify" or "Inspect" from Director are not displayed.

Host from Director:
![director-host](https://user-images.githubusercontent.com/3973350/79536603-bd667880-8080-11ea-9c90-dd36e9052f4c.png)

Service from Director:
![director-service](https://user-images.githubusercontent.com/3973350/79536625-ca836780-8080-11ea-9e0e-055e87d63ee9.png)

**Versions:**
icinga2: v2.12.0-rc1
icingadb: v1.0.0-rc1
icingaweb2: v2.8.0-rc1
icingadb-web: v1.0.0-rc1

**Comment by nilmerg** [comment] 2020-04-17 16:33
Duplicate of #37

**Closed by nilmerg** 2020-04-17 16:33 UTC
