### ISSUE TITLE
Service Downtime icons are not visible in OK state

### ISSUE THREAD

**Issue by mj84** [Icinga/icingadb-web#851] opened 2023-08-25 07:14 UTC
## Describe the bug
Using the old monitoring module, it was possible to see, if there is an active downtime on a service, regardless of its state:
![image](https://github.com/Icinga/icingadb-web/assets/12526366/dd0e7632-6fc5-4433-a601-7315f8160af6)

When using icingadb-web, the downtime icon will not be shown for OK-states:
![image](https://github.com/Icinga/icingadb-web/assets/12526366/388b6b7d-3793-470f-970f-c17ffcf7a9b4)

As soon as the service changes to a non-OK state, the downtime icon will be shown:
![image](https://github.com/Icinga/icingadb-web/assets/12526366/9eab3dda-baec-43b1-b694-3af0edbc263b)

## To Reproduce
As described above.
- Create a downtime for a service
- As long as the service returns OK, the downtime icon won't be displayed
- As soon as the service enters a non-OK state, the downtime icon will be shown

## Expected behavior
The downtime icon should be presented regardless of the service state as it was the case with the Monitoring module.

## Your Environment

* Icinga DB Web version: 1.0.2
* Icinga Web 2 version: 2.11.4
* Web browser: any
* Icinga 2 version: 2.13.6-2
* Icinga DB version: 1.1.0
* PHP version used: 8.1.22
* Server operating system and version: Debian Bookworm

**Comment by nilmerg** [comment] 2023-08-25 09:58
Will be fixed in the next release.

**Comment by nilmerg** [comment] 2023-08-25 09:58
Duplicate of #706

**Closed by nilmerg** 2023-08-25 09:58 UTC
