### ISSUE TITLE
SQL error with restricted permissions

### ISSUE THREAD

**Issue by xschlef** [Icinga/icingadb-web#726] opened 2023-03-21 07:50 UTC
We get an SQL error with restricted access user:

https:///icingaweb2/service?host.name=endo.uni-paderborn.de&name=check_current_load

![image](https://user-images.githubusercontent.com/5031898/226544081-64f4c33e-1699-4130-b2cf-3c299189774c.png)

looks like a badly escaped string?

The restrited permissions are:
- general module access
- icingadb/​filter/​objects a filter based on host vars
- some protected variables

Users with elevated privileges do not face this issue.

Version information:
![image](https://user-images.githubusercontent.com/5031898/226544548-fea5e60f-e429-4a68-8bec-c86aa6b4c27d.png)

ii  icingadb-redis                       7.0.5-1.bullseye                                   all          Persistent key-value database with network interface (metapackage)
ii  icingadb-redis-server                7.0.5-1.bullseye                                   amd64        Persistent key-value database with network interface
ii  icingadb-redis-tools                 7.0.5-1.bullseye                                   amd64        Persistent key-value database with network interface (client)

ii  mariadb-server-10.5                  1:10.5.18-0                             amd64        MariaDB database server binaries

Thank you.

**Comment by sukhwinder33445** [comment] 2023-05-19 09:17
Hi @xschlef,

I cannot reproduce the issue with the given information. Can you tell me what is the role name of user? Is it including any dots or special characters?

Thank you

**Comment by sukhwinder33445** [comment] 2023-05-19 09:20
This issue is probably a duplicate of #742.

**Comment by nilmerg** [comment] 2023-06-07 14:07
Closing for now. Please test the upcoming release and report back if it still does not work.

**Closed by nilmerg** 2023-06-07 14:07 UTC
Labels: needs-feedback
