### ISSUE TITLE
Host list does not show downtimes for OK-Hosts

### ISSUE THREAD

**Issue by adaevitncar** [Icinga/icingadb-web#874] opened 2023-09-22 07:40 UTC
## Describe the bug
The host list in icingadb-web does not visualize a downtime for hosts which are currently in a downtime and are UP. 
The old monitoring showed a corresponding symbol on the right side, something like that is missing in the new view.

## To Reproduce

1. Create a fixed downtime for a host which is currently active
2. Ensure the host is up and running
3. Open icingadb/hosts and look at the host list
4. There's no indication that the host is in downtime

## Expected behavior
Show the downtime for hosts with state UP.

## Screenshots

**Host list**

![01_missing_indicator_downtime](https://github.com/Icinga/icingadb-web/assets/26088367/846d5a4b-658a-4177-8b40-5e3df729b0ff)

**Detail**

![01_missing_indicator_downtime_host_details](https://github.com/Icinga/icingadb-web/assets/26088367/0fc20f5b-508f-4fd1-914c-70071a97b641)

**"Old" monitoring module does it**

![01_missing_indicator_downtime_old_monitoring](https://github.com/Icinga/icingadb-web/assets/26088367/b84da7d2-e7dd-452b-b5b7-1a22e7738869)

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About):  1.0.2 
* Icinga Web 2 version (System - About): 2.11.4
* Web browser: Firefox 117.0.1 (doesn't matter)
* Icinga 2 version (`icinga2 --version`): r2.14.0-1
* Icinga DB version (`icingadb --version`): v1.1.1
* PHP version used (`php --version`): 7.4.33
* Server operating system and version: Debian GNU/Linux 11 (bullseye)

**Comment by yhabteab** [comment] 2023-09-22 08:13
Duplicate of https://github.com/Icinga/icingadb-web/issues/706

**Closed by yhabteab** 2023-09-22 08:13 UTC
