### ISSUE TITLE
Only one Hostgroup is shown in icingadbweb 

### ISSUE THREAD

**Issue by Rolf-Zi** [Icinga/icingadb-web#901] opened 2023-10-02 11:18 UTC
## Describe the bug
If I look at the Details page of a host it shows that the Host is only member of one host group, but there are more than one.

## To Reproduce
Open the Details page of a host

## Expected behavior
It should show all hostgroups to which the host belongs

## Screenshots
see the 2 screenshots

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About):  1.1.0 and 1.0.2
* Icinga Web 2 version (System - About): 2.12.0 and 2.11.4
* Web browser: Chrome
* Icinga 2 version (`icinga2 --version`): 2.14.0
* Icinga DB version (`icingadb --version`): 1.1.1
* PHP version used (`php --version`):  8.2.7 and 7.4.33
* Server operating system and version: Debian 12.1.0 and 11.7.0

## Additional context
I tried several OS and package version.
The problems seems to depend to the version  of icinga-php-library.
icingadb module 1.02 with icinga-php-library 0.12 is okay
icingadb module 1.02 with icinga-php-library 0.13 is not okay
it does not depend to the icingaweb2 or php version

**Comment by Rolf-Zi** [comment] 2023-10-02 11:40
![icingadb102](https://github.com/Icinga/icingadb-web/assets/44290532/d5ac46a8-0e02-45a1-a909-907214ba27e1)

With icinga-php-library 0.12 and icingadb 1.0.2

**Comment by Rolf-Zi** [comment] 2023-10-02 11:42
![icingadb110](https://github.com/Icinga/icingadb-web/assets/44290532/2067c50c-522c-47ba-948c-73c927e3cff5)

With icinga-php-library 0.13   -> NOK 
Only group "Linux" is there, the other groups are missing

**Comment by Rolf-Zi** [comment] 2023-10-04 12:20
This solved my problem :-)
Thank you for your support:

I had to change this permission from
`icingadb/filter/objects = "host.name=*"`

**Comment by nilmerg** [comment] 2023-10-04 14:11
Duplicate of #896

**Closed by nilmerg** 2023-10-04 14:11 UTC
Labels: needs-feedback
