### ISSUE TITLE
Unable to view Host/Services within IcingaDB-Web

### ISSUE THREAD

**Issue by arcadesolutions** [Icinga/icingadb-web#123] opened 2020-08-24 15:53 UTC
Hello,

Not sure if i'm missing something here but i am unable to view the host/service part within the icingdb-web. Always getting an error from ipl:

![image](https://user-images.githubusercontent.com/8624321/91065925-5873ee00-e631-11ea-85b1-f760d6ab5364.png)

**OS**: CentOS Linux release 7.8.2003 (Core)
**IcingaWeb**: icingaweb2-2.8.2-1.el7.icinga.noarch
**Icinga2**: icinga2-2.12.0-1.el7.icinga.x86_64
**IPL**: dd3e987a4b7967d087e1a69f6ebeca4ed4a5d89d / v0.5.0
**icingabd-web**: d4bea474b2d285ab39ddc065eeba80582c61d626 / 1.0.0-rc1
**PHP**: PHP 7.1.30
**Redis**: 5.3.1

The overview itself for hosts/services seems to work, it fails as soon as i click on it.

Let me know if i can provide any more information

**Comment by nilmerg** [comment] 2020-08-25 06:02
Hi, thanks for the report. We already track this as part of #70 and fixed it in https://github.com/Icinga/ipl-html/pull/32. There's no new release of the ipl module yet which incorporates the fix. You'd have to apply it yourself for now.

**Comment by nilmerg** [comment] 2020-08-25 06:02
Duplicate of #70

**Closed by nilmerg** 2020-08-25 06:02 UTC
