### ISSUE TITLE
Host groups: Long host group name pushes state bagdes out of the container

### ISSUE THREAD

**Issue by sukhwinder33445** [Icinga/icingadb-web#366] opened 2021-09-23 08:30 UTC
## Describe the bug
If the group name and also the alias are long, the status badges are pushed out of the container.

## Screensho
![Screenshot 2021-09-23 at 10 19 13](https://user-images.githubusercontent.com/54990055/134476601-d7f0c118-a5f6-4d70-82a0-42566813e651.png)
t

**Comment by nilmerg** [comment] 2021-09-23 08:32
Duplicate of #192

**Closed by nilmerg** 2021-09-23 08:32 UTC
