### ISSUE TITLE
Modify link to Icinga Director is missing

### ISSUE THREAD

**Issue by Meister1900** [Icinga/icingadb-web#644] opened 2022-09-13 14:57 UTC
After upgrading to icingadb-web 1.0.1 the modify (and the inspect) link in a host and in a service are missing.
Especially the modify link was very useful to navigate directly into the service in Icinga director (1.9.1) or to create overrides.

Seems to be fixed by #639

**Comment by nilmerg** [comment] 2022-09-14 07:42
Duplicate of #638

**Closed by nilmerg** 2022-09-14 07:42 UTC
