### ISSUE TITLE
Invalid perfdata breaks the display of a service

### ISSUE THREAD

**Issue by RincewindsHat** [Icinga/icingadb-web#739] opened 2023-04-12 09:38 UTC
## Describe the bug
A non-numerical value in the perfdata will crash the display of a service (or, probably a host, too) and not only not display the pie charts, but also the COMPLETE service.

## To Reproduce
Provide perfdata like `foo=bar;3;4;5;6` in the last check and get this
(URL: `myIcinga.local/icingaweb2/icingadb/service?name=foo&host.name=bla`) :

```
#0 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Util/PerfData.php(467): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Util/PerfData.php(491): Icinga\Module\Icingadb\Util\PerfData->calculatePieChartData()
#2 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/Detail/PerfDataTable.php(108): Icinga\Module\Icingadb\Util\PerfData->asInlinePie(String)
#3 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(294): Icinga\Module\Icingadb\Widget\Detail\PerfDataTable->assemble()
#4 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(514): ipl\Html\HtmlDocument->ensureAssembled()
#5 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(338): ipl\Html\HtmlDocument->render()
#6 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(297): ipl\Html\HtmlDocument->renderUnwrapped()
#7 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(365): ipl\Html\BaseHtmlElement->renderContent()
#8 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(516): ipl\Html\BaseHtmlElement->renderUnwrapped()
#9 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(338): ipl\Html\HtmlDocument->render()
#10 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(297): ipl\Html\HtmlDocument->renderUnwrapped()
#11 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(365): ipl\Html\BaseHtmlElement->renderContent()
#12 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(516): ipl\Html\BaseHtmlElement->renderUnwrapped()
#13 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(338): ipl\Html\HtmlDocument->render()
#14 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(297): ipl\Html\HtmlDocument->renderUnwrapped()
#15 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(365): ipl\Html\BaseHtmlElement->renderContent()
#16 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(516): ipl\Html\BaseHtmlElement->renderUnwrapped()
#17 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(338): ipl\Html\HtmlDocument->render()
#18 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(516): ipl\Html\HtmlDocument->renderUnwrapped()
#19 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Compat/ViewRenderer.php(56): ipl\Html\HtmlDocument->render()
#20 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): ipl\Web\Compat\ViewRenderer->render()
#21 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#22 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(506): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#23 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch(String)
#24 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#25 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#26 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#27 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#28 {main}
```

## Expected behavior
Display the Service ALWAYS. If the perfdata is not ok, then do not paint the pie charts.

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.2
* Icinga Web 2 version (System - About):  Icinga Web 2 Version	2.11.4
* Web browser: google chrome
* Icinga 2 version (`icinga2 --version`): (version: r2.13.7-1)
* Icinga DB version (`icingadb --version`): v1.1.0
* PHP version used (`php --version`): PHP 7.3.33 (cli) (built: Jul 25 2022 11:32:44) ( NTS )
* Server operating system and version: CentOS 7

**Comment by sukhwinder33445** [comment] 2023-05-19 12:32
Hi @RincewindsHat,

I cannot reproduce the issue with the given information. Can you please add the exact steps to reproduce this issue.

Thank you

**Comment by RincewindsHat** [comment] 2023-05-22 15:24
1. Click on "Process check result" on a service
2. Paste `foo=bar;3;4;5;6` into the performance data
3. Fill out the other fields with something
4. Submit

**Comment by nilmerg** [comment] 2023-05-23 06:28
Could be related to #700 and explain why you can't reproduce it anymore @sukhwinder33445

**Comment by sukhwinder33445** [comment] 2023-05-23 07:00
Yes, the issue is reproducible with the latest release commit. It is fixed with the mentioned PR.

**Closed by sukhwinder33445** 2023-05-23 07:00 UTC

**Comment by RincewindsHat** [comment] 2023-05-23 08:07
kk, thanks for your effort :-)
