### ISSUE TITLE
Flexible downtime loads Host/Service tabs

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingadb-web#124] opened 2020-09-02 12:55 UTC
<img width="673" alt="flexible_downtime" src="https://user-images.githubusercontent.com/3973350/91983599-34e52d80-ed2c-11ea-94f6-5bbe0141d188.png">

<img width="676" alt="flexible_service_downtime" src="https://user-images.githubusercontent.com/3973350/91986568-23e8ec00-ed2d-11ea-9017-c436a50dd11c.png">

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

Icinga DB Web version (System - About): 1.0.0.-rc1
Icinga Web 2 version (System - About): 2.8.2
Web browser: Chrome
Icinga 2 version (icinga2 --version): 2.12.0
Icinga DB version (icingadb --version): 1.0.0-rc1
PHP version used (php --version): 7.3.11
Server operating system and version: CentOS 7.8.2003

**Comment by nilmerg** [comment] 2020-10-14 06:52
Just had this myself, but was caused by a form error. So this generally occurs once a form is being re-rendered.

**Comment by nilmerg** [comment] 2021-04-23 08:14
Fixed in master.

**Closed by nilmerg** 2021-04-23 08:14 UTC
Labels: bug
