### ISSUE TITLE
Dashboard migration

### ISSUE THREAD

**Issue by Virsacer** [Icinga/icingadb-web#463] opened 2021-11-24 22:29 UTC
## Describe the bug
When using "Preview this in Icinga DB" on the dashboard, the items are shown in multiline view, but when actually migrating, the items are only shown in singleline view and a scrollbar appears even when there are only two items.

## To Reproduce
1. Install/enable/configure IcingaDB and on the dashboard click the links under "Preview this in Icinga DB".

2. Disable module "monitoring"
3. Enable module "migrate"
4. Go to dashboard

## Expected behavior
The dashboard should look the same after migration as it did in preview mode.

## Screenshots
In preview mode:
![image](https://user-images.githubusercontent.com/8797510/143319564-e9f1e482-4e6c-4d95-9151-b1653861b1bd.png)
After migration:
![image](https://user-images.githubusercontent.com/8797510/143319694-6562d346-6516-4729-a508-3738fff8f9b4.png)

## Your Environment

* Icinga DB Web version (System - About): 1.0.0-rc2
* Icinga Web 2 version (System - About): 2.9.4
* Web browser: Firefox 95.0b11
* Icinga 2 version (`icinga2 --version`): 2.13.2-1
* Icinga DB version (`icingadb --version`): v1.0.0-rc2-dev
* PHP version used (`php --version`): 8.0.8
* Server operating system and version: Ubuntu 21.10

**Comment by nilmerg** [comment] 2021-11-25 08:09
Hi,

I can't reproduce that, neither with Web 2 v2.9.5 nor with the master. Note that just enabling the `migrate` module won't do anything.

Did you disable `monitoring` in the UI or on CLI? Though I tried both, and still cannot reproduce it.

Try pushing F12 (opening the developer tools in the browser) and take a look at the console. Are there any errors?

**Comment by Virsacer** [comment] 2021-11-25 10:15
Oh that was a typo - I'm also using 2.9.5

I (dis|en)abled them in the UI.
Something happend when I enabled "migrate" for the first time, but now when I have only monitoring or icingadb enabled the dashboard changes without the need for "migrate".

Scrollbars also appear on Iexplorer, but not on Chromium.
Firefox console shows:
> Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:1:3298
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:1:3739
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:1:3901
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:1:4062
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:1:4523
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:1:4812
Unknown property ‘-moz-box-shadow’.  Declaration dropped. icinga.min.css:1:4952
Unknown property ‘-moz-box-shadow’.  Declaration dropped. icinga.min.css:1:4987
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:1:5590
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:1:5805
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:1:6258
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:1:6491
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:1:9353
Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. icinga.min.css:1:15959
Unknown property ‘speak’.  Declaration dropped. icinga.min.css:1:39260
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. icinga.min.css:1:39417
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. icinga.min.css:4:57
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:57819
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:60266
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:60917
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:61222
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:61412
Unknown property ‘speak’.  Declaration dropped. icinga.min.css:4:163070
Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped. icinga.min.css:4:168843
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:172476
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. icinga.min.css:4:172817
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:174108
Unrecognized at-rule or error parsing at-rule ‘@-ms-keyframes’. icinga.min.css:4:175868
Unrecognized at-rule or error parsing at-rule ‘@-o-keyframes’. icinga.min.css:4:175918
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:181767
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:184297
Unknown property ‘-moz-box-shadow’.  Declaration dropped. icinga.min.css:4:184584
Keyframe rule ignored due to bad selector. icinga.min.css:4:187040
Keyframe rule ignored due to bad selector. icinga.min.css:4:187155
Keyframe rule ignored due to bad selector. icinga.min.css:4:187297
Keyframe rule ignored due to bad selector. icinga.min.css:4:187412
Unrecognized at-rule or error parsing at-rule ‘@-o-keyframes’. icinga.min.css:4:187499
Unrecognized at-rule or error parsing at-rule ‘@-ms-keyframes’. icinga.min.css:4:187752
Keyframe rule ignored due to bad selector. icinga.min.css:4:188051
Keyframe rule ignored due to bad selector. icinga.min.css:4:188166
Keyframe rule ignored due to bad selector. icinga.min.css:4:188320
Keyframe rule ignored due to bad selector. icinga.min.css:4:188455
Keyframe rule ignored due to bad selector. icinga.min.css:4:188587
Keyframe rule ignored due to bad selector. icinga.min.css:4:188717
Keyframe rule ignored due to bad selector. icinga.min.css:4:188844
Keyframe rule ignored due to bad selector. icinga.min.css:4:188980
Keyframe rule ignored due to bad selector. icinga.min.css:4:189118
Keyframe rule ignored due to bad selector. icinga.min.css:4:189290
Keyframe rule ignored due to bad selector. icinga.min.css:4:189425
Keyframe rule ignored due to bad selector. icinga.min.css:4:189557
Keyframe rule ignored due to bad selector. icinga.min.css:4:189687
Keyframe rule ignored due to bad selector. icinga.min.css:4:189814
Keyframe rule ignored due to bad selector. icinga.min.css:4:189950
Keyframe rule ignored due to bad selector. icinga.min.css:4:190088
Unrecognized at-rule or error parsing at-rule ‘@-o-keyframes’. icinga.min.css:4:190190
Unrecognized at-rule or error parsing at-rule ‘@-ms-keyframes’. icinga.min.css:4:191156
Keyframe rule ignored due to bad selector. icinga.min.css:4:192183
Keyframe rule ignored due to bad selector. icinga.min.css:4:192318
Keyframe rule ignored due to bad selector. icinga.min.css:4:192450
Keyframe rule ignored due to bad selector. icinga.min.css:4:192580
Keyframe rule ignored due to bad selector. icinga.min.css:4:192707
Keyframe rule ignored due to bad selector. icinga.min.css:4:192843
Keyframe rule ignored due to bad selector. icinga.min.css:4:192981
Unknown property ‘-moz-filter’.  Declaration dropped. icinga.min.css:4:206907
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. icinga.min.css:4:207347
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. icinga.min.css:4:214098
Unknown pseudo-class or pseudo-element ‘-moz-submit-invalid’.  Ruleset ignored due to bad selector. icinga.min.css:4:214393
Unknown property ‘-moz-box-shadow’.  Declaration dropped. icinga.min.css:4:218731
Unknown property ‘-moz-box-shadow’.  Declaration dropped. icinga.min.css:4:218772
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:218978
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:222877
Unknown pseudo-class or pseudo-element ‘-ms-expand’.  Ruleset ignored due to bad selector. icinga.min.css:4:223502
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:224797
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:227024
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:228380
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. icinga.min.css:4:234126
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:237355
Unknown property ‘-moz-border-radius’.  Declaration dropped. icinga.min.css:4:246759
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:246838
Unknown property ‘-moz-box-shadow’.  Declaration dropped. icinga.min.css:4:246936
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:247983
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:253203
Unknown property ‘-moz-box-shadow’.  Declaration dropped. icinga.min.css:4:258021
Unknown property ‘-moz-box-shadow’.  Declaration dropped. icinga.min.css:4:258068
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:258958
Unknown property ‘-moz-box-shadow’.  Declaration dropped. icinga.min.css:4:268763
Error in parsing value for ‘padding-left’.  Declaration dropped. icinga.min.css:4:269515
Error in parsing value for ‘padding-right’.  Declaration dropped. icinga.min.css:4:269574
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:271390
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:273680
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:284672
Unknown property ‘-moz-box-shadow’.  Declaration dropped. icinga.min.css:4:291167
Unknown property ‘-moz-box-shadow’.  Declaration dropped. icinga.min.css:4:291198
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:293830
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:295081
Unknown property ‘-moz-box-shadow’.  Declaration dropped. icinga.min.css:4:297306
Unknown property ‘-moz-box-shadow’.  Declaration dropped. icinga.min.css:4:297338
Unknown property ‘-moz-box-shadow’.  Declaration dropped. icinga.min.css:4:300659
Unknown property ‘-moz-box-shadow’.  Declaration dropped. icinga.min.css:4:300690
Unknown property ‘-moz-box-shadow’.  Declaration dropped. icinga.min.css:4:303202
Unknown property ‘-moz-box-shadow’.  Declaration dropped. icinga.min.css:4:303233
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:303594
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:305188
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:307377
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:307697
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:315690
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:321022
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:321881
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:323010
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:326721
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:329975
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:331172
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:333348
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:333667
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:337188
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:339917
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:340798
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:343091
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:343463
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:348245
Unknown property ‘-moz-background-clip’.  Declaration dropped. icinga.min.css:4:352384
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. icinga.min.css:4:357563

But now I noticed that under `/dashboard/settings` the urls contain `&view=minimal&limit=32`
Shoud that not be something like`&view=common&limit=10`?

**Comment by nilmerg** [comment] 2021-11-25 11:23
> Scrollbars also appear on Iexplorer, but not on Chromium.

IE is not supported by Icinga DB Web.

The Firefox log doesn't show anything suspicious. But now I noticed you're running a developer build, does it occur with the latest stable?

> Shoud that not be something like `&view=common&limit=10`?

Icinga DB Web has different view modes now. The default dashboards use the minimal version to be able to show more entries.

**Comment by Virsacer** [comment] 2021-11-25 20:55
Firefox Developer Edition ;-)
Just downloaded 94.0.2, but it looks the same way...

Then the preview should preview exacly that.
I would prefer it the other direction, but ok...

**Comment by nilmerg** [comment] 2022-07-18 07:50
We had no similar reports until now. I suspect a browser issue. Closing.

**Closed by nilmerg** 2022-07-18 07:50 UTC

**Comment by nilmerg** [comment] 2022-07-19 07:41
Being on the dashboard, the view mode is minimal. If that's not desired, the dashlets should be edited and the `view` parameter removed.

Leaving the dashboard, there is indeed no need to force a specific view mode. I'll think about to change this.

> And the scrollbars are also still there (in minimal view) in all three browsers...

That's what I and none of my colleagues could ever reproduce. Neither did anyone else come up with the same problem. Can't help you with that.

**Comment by lippserd** [comment] 2022-07-22 11:16
> > And the scrollbars are also still there (in minimal view) in all three browsers...
> 
> That's what I and none of my colleagues could ever reproduce. Neither did anyone else come up with the same problem. Can't help you with that.

@Virsacer Could you please export the HTML when the scrollbar problem occurs? This may help to identify the issue.

**Comment by Virsacer** [comment] 2022-07-23 09:53
> Leaving the dashboard, there is indeed no need to force a specific view mode. I'll think about to change this.

That would be nice :-)

I found out, how to reproduce the scrollbars in a new installation:
Add `icon_image = "img/favicon.png"` to the `generic-service` template.
I'm using 32x32px images for all services...
