### ISSUE TITLE
Clarify handled states in list items by adding titles to state visuals

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingadb-web#916] opened 2023-10-24 13:13 UTC
## Describe the bug
We use icons for the visuals of handled state list items. It's probably not obvious for users what these icons mean, so we should at least clarify that by adding titles.

## To Reproduce
* Navigate to a host or service list, that contain an item, that is in a handled state.
* The only way to know what the state icon implies and the meaning of the different icons is to look it up in code

## Possible Solution
Add title attributes to the state visual to clarify, what the exact it state implies and help users learn in long term, what the icons mean.

## Screenshots
![Screen Shot 2023-10-24 at 15 26 11](https://github.com/Icinga/icingadb-web/assets/6977434/acf30b90-1968-40b8-b37a-f243cb3f9599)

## Your Environment
![Screen Shot 2023-10-24 at 15 27 42](https://github.com/Icinga/icingadb-web/assets/6977434/6570b674-1e0d-49b6-a86f-b66b4345b56e)

**Comment by nilmerg** [comment] 2023-10-25 07:38
Duplicate of #819

**Closed by nilmerg** 2023-10-25 07:38 UTC
