### ISSUE TITLE
check_period missing

### ISSUE THREAD

**Issue by Virsacer** [Icinga/icingadb-web#688] opened 2022-11-23 15:02 UTC
## Describe the bug
As mentioned in my moved issue https://github.com/Icinga/icinga2/issues/9596 IcingaDB does not display the value of `check_period` on the service page.

## To Reproduce
Set a `check_period`

## Expected behavior
Show the `check_period` in IcingaDB like in the monitoring module.

## Your Environment
* Icinga DB Web version (System - About): 1.0.2
* Icinga Web 2 version (System - About): 2.11.2
* Icinga 2 version (`icinga2 --version`): 2.13.6
* Icinga DB version (`icingadb --version`): 1.1
* PHP version used (`php --version`): 7.3.33
* Server operating system and version: Oracle Linux 7

**Comment by carraroj** [comment] 2023-04-05 10:01
ref/NC/780817

**Comment by nilmerg** [comment] 2023-04-05 10:06
Duplicate of #109

**Closed by nilmerg** 2023-04-05 10:06 UTC
