### ISSUE TITLE
HostGroup filter is wrong within a custom dashboard

### ISSUE THREAD

**Issue by arcadesolutions** [Icinga/icingadb-web#127] opened 2020-10-01 08:40 UTC
## Describe the bug
Created my own dashboard with hostgroups and a custom filter. If i want to check the services/hosts within this dashboard, the result won't show because the filter is wrong.

## To Reproduce

1. Add a filter under Host Groups in IcingaDB (e.g hostgroup.name=h_grp_*)
2. Store the results in a new custom dashboard
3. View services/hosts within this board
4. Not results show up

## Expected behavior
Should see the overview of these services/hosts (e.g all critical services for that hostgroup)

## Screenshots
![image](https://user-images.githubusercontent.com/8624321/94786827-c7cbc300-03d1-11eb-9e17-a8e2610608d8.png)

![image](https://user-images.githubusercontent.com/8624321/94786899-ddd98380-03d1-11eb-9e24-ce3a4738e237.png)

![image](https://user-images.githubusercontent.com/8624321/94787293-6b1cd800-03d2-11eb-8736-f0adb17f1119.png)

The problem is my second custom filter which i used to create that dashboard. If i remove it, the content gets shown.

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

- Icinga DB Web version (System - About): 1.0.0-rc1
- Icinga Web 2 version (System - About): 2.8.2
- Web browser: Chrome 84.0.4147.135
- Icinga 2 version (icinga2 --version): 2.12.0-1
- Icinga DB version (icingadb --version): v1.0.0-rc1
- PHP version used (php --version): 7.1.26
- Server operating system and version: CentOS 7.5.1804

**Comment by Al2Klimov** [comment] 2020-10-05 16:17
Hello @arcadesolutions and thank you for reporting!

Your examples work for me:

![Bildschirmfoto 2020-10-05 um 18 12 14](https://user-images.githubusercontent.com/6053266/95105065-ebc33780-0736-11eb-90d2-fdddd2fb8407.png)
![Bildschirmfoto 2020-10-05 um 18 12 22](https://user-images.githubusercontent.com/6053266/95105069-ed8cfb00-0736-11eb-8e58-f0d14cebbd64.png)
![Bildschirmfoto 2020-10-05 um 18 14 17](https://user-images.githubusercontent.com/6053266/95105071-ee259180-0736-11eb-9398-ea46cdf3e08e.png)

Please provide instructions to reproduce this from scratch.

Best,
AK

**Comment by arcadesolutions** [comment] 2020-10-07 14:00
Hey AK,

Sure let me provide some instructions to recreate this.

**Initial overview**

![image](https://user-images.githubusercontent.com/8624321/95336364-e25dda80-08b0-11eb-8551-c962339138f8.png)

**Create the filter**

![image](https://user-images.githubusercontent.com/8624321/95336592-23ee8580-08b1-11eb-9f41-adf7a3e046c2.png)

**Create a new dashboard based on the filter**

![image](https://user-images.githubusercontent.com/8624321/95338544-55685080-08b3-11eb-93f9-75ad79b5cb44.png)

**New dashboard**

![image](https://user-images.githubusercontent.com/8624321/95338942-c3ad1300-08b3-11eb-90af-5d2e236009fc.png)

**Click on the object (eg. Host)**

![image](https://user-images.githubusercontent.com/8624321/95339263-2bfbf480-08b4-11eb-88cf-7a31f9dc53fb.png)

Nothing gets displayed, when remove my filter (hostgroup.name = h_grp_*) it works. 

![image](https://user-images.githubusercontent.com/8624321/95340532-92354700-08b5-11eb-9700-d9186f49903c.png)

So I'd expect that as soon as I click on either the services or hosts for this hostgroup, my customer filter gets removed and the objects are displayed. 

Hope that helps

Regards
Reto

**Comment by Al2Klimov** [comment] 2020-10-07 15:47
Note: Neither pulling Icinga Web, nor the IcingaDB module helps.

**Comment by Al2Klimov** [comment] 2020-10-07 16:16
@nilmerg We're auto-calculating columns based on the model classes, right?

Also I've figured out that it's not about the column being invalid – an invalid column would be reported explicitly.

**Comment by nilmerg** [comment] 2021-04-30 14:58
Don't know when and how, but this is fixed in master. Can't reproduce it at least.

**Closed by nilmerg** 2021-04-30 14:58 UTC
Labels: further-investigation
